<a href="https://colab.research.google.com/github/70ekanetugu/MLColab/blob/main/python/math_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# シグマ
import numpy as np

a = np.array([1,3,2,5,4])
y = np.sum(a)
print(y)

15


In [2]:
# ネイピア数
print(np.e)
print(np.exp(1))

2.718281828459045
2.718281828459045


In [4]:
# 自然対数
print(np.log(np.e))
print(np.log(np.exp(2)))
print(np.log(np.exp(12)))

1.0
2.0
12.0


In [14]:
# ベクトル(1次元のNumpy配列)
a = np.array([3,2,1])
b = np.array([-2.3, 0.25, -1.2, 1.8,0.41])
print(a)
print(b)

# 行列(2次元のNumpy配列)
a = np.array([[1,0,5], 
              [4,3,2]])
print(a)
b = np.array([[1.2, 0.18],
              [2.3, -0.31],
              [1, 2]])
print(b)

## 行列積
print("行列積: ", np.dot(a, b))

## アダマール積(=要素ごとの積)
b = np.array([[1.2, 0.18, 1],
              [2.3, -0.31, 2]])
print("アダマール積: ", a * b)

# 転置
print(a.T)


[3 2 1]
[-2.3   0.25 -1.2   1.8   0.41]
[[1 0 5]
 [4 3 2]]
[[ 1.2   0.18]
 [ 2.3  -0.31]
 [ 1.    2.  ]]
行列積:  [[ 6.2  10.18]
 [13.7   3.79]]
アダマール積:  [[ 1.2   0.    5.  ]
 [ 9.2  -0.93  4.  ]]
[[1 4]
 [0 3]
 [5 2]]
